export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_ADD_ITEM_DB_REQUEST = 'CART_ADD_ITEM_DB_REQUEST'
export const CART_ADD_ITEM_DB_SUCCESS = 'CART_ADD_ITEM_DB_SUCCESS'
export const CART_ADD_ITEM_DB_FAIL = 'CART_ADD_ITEM_DB_FAIL'

export const CART_ITEMS_LIST_REQUEST = 'CART_ITEMS_LIST_REQUEST'
export const CART_ITEMS_LIST_SUCCESS = 'CART_ITEMS_LIST_SUCCESS'
export const CART_ITEMS_LIST_FAIL = 'CART_ITEMS_LIST_FAIL'

export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'